### ISSUE TITLE
add searchbar recommendations for basic maths section

### ISSUE THREAD

**Issue by khareyash05** [sairish2001/makesmatheasy#960]
I would like to add searchbar recommendations for basic maths section

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

I would like you to create a Algorithm, which will serve this purpose
as Adding multiple if-else if-.... conditions are difficult to manage, in future.
Since similar steps are repeating for every condition.
so I would like you to maintain a Array or json data, as I done in `function openit() {}` .

**Comment by khareyash05** [comment]
@sairish2001 I am sorry I didnt check out this until now and i created a PR 
 I will do the same from this PR onwards
SHould i create an array and use map function to get them?

**Comment by sairish2001** [comment]
> @sairish2001 I am sorry I didnt check out this until now and i created a PR 
>  I will do the same from this PR onwards
> SHould i create an array and use map function to get them?

Yes anything you like
